name: Deploy Laravel Project on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.0' # Specify your PHP version

      - name: Change directory to src
        run: cd src
        
      - name: Copy .env
        run: php -r "file_exists('src/.env') || copy('src/.env.example', 'src/.env');"

      - name: Install Dependencies
        run: cd src && composer update --ignore-platform-reqs

      - name: Generate key
        run: cd src && php artisan key:generate

      - name: Generate storage link
        run: cd src && php artisan storage:link
        
      - name: Directory Permissions
        run: cd src && chmod -R 777 storage bootstrap/cache

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.YOURSITE_FTP_SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.YOUR_PASSWORD }}
          local-dir: src/
